# Site settings
title: Feiya Ou
email: f/xdknbyqk
url: https://feiyaou.github.io/
description: "This is a portfolio website for Feiya Ou,who is a front-end developer, user experience designer and graphic artist. "
keywords: "Feiya Ou,Web Developer,UX Designer,Graphic Artist"
skills: "Web Developer - User Experience Designer - Graphic Artist"
meta_author: Ou Feiya

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,188,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Feiya Ou
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/FeiyaOu

# Postal address (add as many lines as necessary)
address:
  - line: Toronto
  - line: ON, Canada

# Credits content
# credits: 'This website is built using a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown

permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
